---
project_name: Elsewhere
project_url: "https://github.com/dharmafly/elsewhere"
version: 0.0.4
jquery_no_conflict: true
theme: seagrass
twitter_url: "https://twitter.com/dharmafly"
twitter_name: Dharmafly
lang: javascript
scripts: 
  - src: "https://github.com/downloads/dharmafly/pablo/pablo.min.js"
stylesheets: null
quote: 
  quote: It is living and ceasing to live that are imaginary solutions. Existence is elsewhere.
  cite: Andre Breton
ga_id: "UA-34978047-3"
download_links: 
  - text: Elsewhere
    subtext: "v{{ version }}"
    href: "https://github.com/dharmafly/elsewhere/zipball/master"
    title: Master branch zip
sections: 
  - path: /index.html
    name: Overview
  - path: /reference/index.html
    name: Reference
safe: false
future: true
lsi: false
highlighter: rouge
markdown: kramdown
permalink: "/:title"
baseurl: /
exclude: 
  - README.md
  - FiddlerRules.farx
